echo -e "\033[0;36m====== RM-TOOL:: generating support library  ======\e[0;39m"
cd kinblock
if [ ! -d "dataview" ]; then
    echo -e "\033[0;36mERROR: Please copy the dataview directory (generated by TASTE) into the kinblock directory. It is required to build the solver bridge.\e[0;39m"
    exit 1
fi
cd rmtool
make
ORCHESTRATOR_OPTIONS+=" -e x86_partition:`pwd`"
ORCHESTRATOR_OPTIONS+=" -l x86_partition:`pwd`/libkinsolverbridge.a"
cd ..
cd ..
echo -e "\e[36m====== RM-TOOL:: support library generated in kinblock/rmtool ======\e[39m"
ORCHESTRATOR_OPTIONS+=" -l x86_partition:/usr/local/lib/libur5.so"
ORCHESTRATOR_OPTIONS+=" -l x86_partition:/usr/local/lib/libilkeigenbackend.so"
